### ISSUE TITLE
Latest Github UI changes breaks this plugin

### ISSUE THREAD

**Issue by zhimsel** [Yatser/prettypullrequests#38]
Seems that with GH's new menu-based file selector in PRs, this plugin no longer works...

**Comment by Yatser** [comment]
Thanks @zhimsel, I haven't noticed this yet myself but I will be on the lookout for it, along with my coworkers, and hopefully we can figure out what needs to change.

Do you have any extra information about what you're seeing? Is it just clicking on the title bar of diffs that doesn't work anymore? Is there a collapse diff bar at the bottom of a diff that still works?

**Comment by zhimsel** [comment]
No, clicking the text in the titlebar still works, as does the bottom bar.
I remember something you could click at the top of the list of diffs that
would collapse all of them at once (so you can expand only one). Unless I'm
mistaken, and that wasn't a functionality of this plugin, but it was
instead from stock Github.


--
Zach Himsel
zach@himsel.net
http://zach.himsel.net

**Comment by Yatser** [comment]
No no, that is from me. In fact, github made me change the logo so that it was not using the stock logo, so that people wouldn't confuse it being official haha. 

However, the latest version of chrome moved the icons from the address bar to the right of the address bar. And... unfortunately my logo is black on transparent... check out this screenshot of one of my chrome users: 
<img width="167" alt="screen shot 2016-03-23 at 1 51 08 pm" src="https://cloud.githubusercontent.com/assets/1159120/13998733/53494600-f0fe-11e5-8e5b-4c92b65f33bb.png">

Here is the logo on a dark but slightly lighter background:
<img width="78" alt="screen shot 2016-03-23 at 1 51 36 pm" src="https://cloud.githubusercontent.com/assets/1159120/13998743/666cd8be-f0fe-11e5-89b2-553973fd2680.png">

So likely the logo is there, in its new place, and you either didn't realize it had moved, or can't see it due to the logo. I'm going to change the logo to be black on white so that it shows better on dark backgrounds.

**Comment by zhimsel** [comment]
> No no, that is from me.

Ah. Then never mind :)
