### ISSUE TITLE
Can't Collapse Diff in Pull Request

### ISSUE THREAD

**Issue by ushuz** [Yatser/prettypullrequests#45]
Today I noticed that diff collapsing stops working. I checked **localStorage** and found something like `ppr|my|repo|#201|undefined`, it seems the extension can't get the correct diff-id. The extension works just fine for me before, maybe caused by some updates of GitHub?

**Comment by Yatser** [comment]
Hey ushuz,

Yup, I believe a GitHub update today broke the extension. The classes on the diffs have changed. A fix is coming!

**Comment by janhartigan** [comment]
@Yatser any update on this? Missing this extension :(

**Comment by Yatser** [comment]
I know @janhartigan haha, I'm hearing that a lot from my coworkers and other devs too.

It's a bit harder than I thought because the classes and structure has changed quite a bit on github.com, but I still have to support github enterprise which doesn't change. Up until now, despite having minor differences of class names, the structure between those two was still the same, but not anymore.

So, I have been thinking about how to do it, and decided I have to split into separate content scripts for each (probably with a common file as well). It's just been more work than I thought it would to fix and haven't gotten it all done yet. A fix IS still coming, my apologies for taking longer than anticipated.

**Comment by janhartigan** [comment]
@Yatser excellent thank you for explaining that

**Comment by Yatser** [comment]
Hey all,

I just published version 2.10.3, which should restore collapsing. I have a lot more cleanup work to do on this now that I've split github and github enterprise into two separate files, but a fix was long overdue and I wanted to get it out.

It will take some time for the update to propagate out.

When someone other than me confirms that it is indeed working, I'll close this issue. Thanks for everyone's patience.

**Comment by janhartigan** [comment]
@Yatser it works for me. Glad to have everything back!
